/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_cpurenderer_free: (a: number, b: number) => void;
export const __wbg_vellorenderer_free: (a: number, b: number) => void;
export const cpurenderer_freeAsset: (a: number, b: number) => void;
export const cpurenderer_getAnimationMeta: (a: number, b: number, c: number, d: number, e: number) => any;
export const cpurenderer_getAnimationNames: (a: number, b: number) => [number, number];
export const cpurenderer_loadAsset: (a: number, b: number, c: number, d: number) => number;
export const cpurenderer_new: () => number;
export const cpurenderer_renderFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const vellorenderer_batchCopy: (a: number, b: number, c: number, d: number) => number;
export const vellorenderer_createAtlas: (a: number, b: number, c: number) => any;
export const vellorenderer_flushFrames: (a: number, b: number) => void;
export const vellorenderer_freeAllTextures: (a: number) => void;
export const vellorenderer_freeAsset: (a: number, b: number) => void;
export const vellorenderer_freeTexture: (a: number, b: number) => void;
export const vellorenderer_getAnimationInfo: (a: number, b: number, c: number, d: number) => any;
export const vellorenderer_getAnimationMeta: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const vellorenderer_getAnimationNames: (a: number, b: number) => [number, number];
export const vellorenderer_getFrameSize: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const vellorenderer_init: () => any;
export const vellorenderer_loadAsset: (a: number, b: number, c: number, d: number) => number;
export const vellorenderer_loadSwfBundle: (a: number, b: number, c: number, d: number, e: number) => number;
export const vellorenderer_queueFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => any;
export const vellorenderer_renderAnimationStrip: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const vellorenderer_renderFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => any;
export const vellorenderer_renderFrameToAtlas: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => any;
export const vellorenderer_renderSwfFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const vellorenderer_renderZoneMaskFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const vellorenderer_renderZoneMaskStrip: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const vellorenderer_setSwfPlayerColors: (a: number, b: number, c: number, d: number) => void;
export const vellorenderer_swfAnimFrameCount: (a: number, b: number, c: number, d: number, e: number) => number;
export const vellorenderer_swfBundleFrameRate: (a: number, b: number, c: number) => number;
export const vellorenderer_swfTileAnimKind: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasm_bindgen_f1f22d1002885764___convert__closures_____invoke___js_sys_f0cfdae76522e648___Function_fn_wasm_bindgen_f1f22d1002885764___JsValue_____wasm_bindgen_f1f22d1002885764___sys__Undefined___js_sys_f0cfdae76522e648___Function_fn_wasm_bindgen_f1f22d1002885764___JsValue_____wasm_bindgen_f1f22d1002885764___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_f1f22d1002885764___convert__closures_____invoke___wasm_bindgen_f1f22d1002885764___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_f1f22d1002885764___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_f1f22d1002885764___convert__closures_____invoke___wasm_bindgen_f1f22d1002885764___JsValue______true_: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
